export const templates: any = {
  simple: [
    '@types/react@latest',
    '@types/react-dom@latest',
    '@peajs/core@latest',
    'react@latest',
    'react-dom@latest',
    'pea-cli@latest',
  ],
  'with-router': [
    '@types/react@latest',
    '@types/react-dom@latest',
    '@peajs/core@latest',
    '@peajs/router@latest',
    'pea-plugin-router@latest',
    'react@latest',
    'react-dom@latest',
    'pea-cli@latest',
    'stook@latest',
  ],

  'admin': [
    "@types/styled-components@latest",
    "@types/classnames@latest",
    '@types/react@latest',
    '@types/react-dom@latest',
    '@peajs/core@latest',
    '@peajs/router@latest',
    "@peajs/drawer@latest",
    "@peajs/graphql@latest",
    "@peajs/i18n@latest",
    "@peajs/modal@latest",
    "@peajs/rest@latest",
    "antd@latest",
    "classnames@latest",
    'pea-plugin-router@latest',
    "pea-plugin-antd@latest",
    "pea-plugin-drawer@latest",
    "pea-plugin-graphql@latest",
    "pea-plugin-less@latest",
    "pea-plugin-modal@latest",
    "pea-plugin-rest@latest",
    "pea-plugin-styled-jsx@latest",
    'react@latest',
    'react-dom@latest',
    'pea-cli@latest',
    "styled-components@latest",
  ],
}
